spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/home-db
    username: postgres
    password: root
  liquibase:
    enabled: true

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

logging:
  level:
    root: INFO
    com:
      koval: DEBUG
  file:
    name: logs/app.log

springdoc:
  swagger-ui:
    tagsSorter: alpha

aws:
  region: eu-north-1
  access-key: AKIASPIDHS6XF4TU32WS
  secret-access-key: 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
  s3-bucket-name: home-koval-countries-flags